config/routes.rb
Rails.application.routes.draw do
	get 'help', to: 'pages#help'
	get 'about', to: 'pages#about'
	get 'contact', to: 'pages#contact'
	get 'estimate', to: 'pages#estimate'
	get 'packages', to: 'pages#packages'
	root to: "pages#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	def index
	end

	def estimate
	end

	def help
	end

	def contact
	end

	def packages
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DetailingService</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
  	<%= render('shared/nav') %>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<div class="container">
	<div class="ro">
		<h1>About</h1>
	</div>
</div>

app/views/pages/contact.html.erb
<div class="container">
	<div class="row">
		<h1>CONTACT</h1>
	</div>
</div>

app/views/pages/estimate.html.erb
<div class="container">
	<div class="row">
		<div class="card m-2">
			<h3 class="card-header">Detail Estimate</h3>
			<div class="card-body pb-2">
				Fill out the form below to see how much a complete detail service will cost for your vehicle.
			<hr>
				<small>
					Let's get started! Select the options below that best descibe your vehicle and the services you would like for us to provide.
				</small>
			</div>
		</div>
	</div>
</div>

app/views/pages/help.html.erb
<div class="container">
	<div class="row">
		<h1>HELP</h1>
	</div>
</div>

app/views/pages/index.html.erb
<div class="container">
	<div class="row p-2">
		<div>
			<p class="lead">
				Call us to schedule your mobile auto detailing in Destin, Sandestin, Santa Rosa Beach, or Fort Walton Beach areas! We come and do the rest for you!
			</p>
			<button class="btn btn-block btn-primary mb-4">
				<%= fa_icon('phone', class: 'outline pr-1') %> 
				Click to Call Us!
			</button>
		</div>
		<div>
			<h4>About Us</h4>
			<p>
				Even an old car can look new with help from an auto detailing service! Car detailing is what causes some vehicles to look so bright and shiny. Getting it detailed is a great way to make heads turn.
			</p>
		</div>
		<div>
			<h4>Services</h4>
			<p>
				We offer many auto and boat detailing services options. It's the convenient way to keep your car and boat healthy and in top condition.
			</p>
		</div>
		<div>
			<h4>Packages</h4>
			<p>
				Choose of our different options of packages, which one is the right for you?
			</p>
		</div>
	</div>
</div>

app/views/pages/packages.html.erb
<div class="container">
	<div class="row m-2">
		<h1>Detailing Packages</h1>
			We have many different packages for you to choose from for your vehicle cleaning needs. Please review the packages below and contact us today to schedule a vehicle detail.
	</div>
</div>

app/views/shared/_nav.html.erb
<nav class="navbar navbar-expand-md navbar-dark bg-dark">
  <a class="navbar-brand" href="#">DNN AUTO DETAILING</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <%= link_to "Home", root_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Packages", packages_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Detail Estimate", estimate_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "About Us", about_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Help", help_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Contact Us", contact_path, class: "nav-link" %>
      </li>
    </ul>
  </div>
</nav>